[environment]
zone = BCUFR
environment = P

[mongo_db]
mongo_db = records
mongo_col = nz_records

[process]
sru_url = https://swisscovery.slsp.ch/view/sru/41SLSP_BCUFR
mapping_iz_to_nz = data/mms_id_mapping_from_iz_to_nz.csv
existing_records = data/analytical_rec_bcufr.csv
update_delay_days = 80
creation_year_threshold = 2026
f990a_txt = bfdnoanauto
f998a_txt = no_inventory_analytical
# Production
set_of_parents_id = 15418570690005509
# Sandbox
# set_of_parents_id = 15463912270005509
log_level = INFO

[report]
mongo_db_report = automated_processes
mongo_col_report = bcufr_analytical_records
